PROJECT(cpack-rpm)

set(CPACK_RPM_PACKAGE_RELEASE epl8)
set(CPACK_RPM_PACKAGE_RELEASE_DIST YES)
set(CPACK_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_RELEASE_DIST "")
set(CPACK_RPM_PACKAGE_VENDOR "DefenceX")
set(CPACK_RPM_PACKAGE_SUMMARY "A render engine for displaying a Human Machine Interface (HMI) on a military vehicle's embedded display.")
set(CPACK_RPM_FILE_NAME  "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CPACK_RPM_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}.rpm")
set(CPACK_RPM_PACKAGE_REQUIRES "glibc-static, cairo-devel, libXext-devel, ffmpeg-libs, protobuf, gtk3-devel")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "${CMAKE_SOURCE_DIR}/scripts/cmake/postinst")
