project(${CPACK_PACKAGE_NAME})

set(CPACK_GENERATOR "NSIS")

## Windows
set(CPACK_SYSTEM_NAME win64)
# set(CPACK_SET_DESTDIR FALSE)
set(CPACK_PACKAGE_INSTALL_DIRECTORY "vivoe-lite")
#set(CPACK_COMPONENTS_ALL COMPONENTS)
set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "Vivoe Lite")
# set(CPACK_PACKAGING_INSTALL_PREFIX "vivoe-lite")

# NSIS
set(CPACK_MONOLITHIC_INSTALL TRUE)
set(CPACK_NSIS_MUI_ICON ${CMAKE_SOURCE_DIR}/images/favicon.ico)
set(CPACK_NSIS_MUI_UNIICON ${CMAKE_SOURCE_DIR}/images/favicon.ico)
set(CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP ${CMAKE_SOURCE_DIR}\\\\images\\\\NSIS_Installer_Welcome.bmp)
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP ${CMAKE_SOURCE_DIR}\\\\images\\\\NSIS_Installer.bmp)
set(CPACK_NSIS_COMPONENT_INSTALL OFF)
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH OFF)
set(CPACK_NSIS_DISPLAY_NAME "Vivoe Lite installer")
set(CPACK_NSIS_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE)
set(CPACK_NSIS_INSTALLED_ICON_NAME ${CMAKE_SOURCE_DIR}/images/favicon.ico)
set(CPACK_NSIS_HELP_LINK "https://defencex.ai/downloads.html")
set(CPACK_NSIS_URL_INFO_ABOUT "https://defencex.ai")
set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
    SetOutPath $INSTDIR\\\\bin
    CreateShortCut \\\"$DESKTOP\\\\${PROJECT_NAME}.lnk\\\" \\\"$INSTDIR\\\\bin\\\\hmi-display.exe\\\"
")

