
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/version VERSION_INFO)
set(VERSION_INFO_LIST ${VERSION_INFO} )
separate_arguments(VERSION_INFO_LIST UNIX_COMMAND "${VERSION_INFO}")
list(GET VERSION_INFO_LIST 0 CMAKE_MAJOR_VERSION)
list(GET VERSION_INFO_LIST 1 CMAKE_MINOR_VERSION)
list(GET VERSION_INFO_LIST 2 CMAKE_PATCH_VERSION)
execute_process(COMMAND git rev-parse --short HEAD OUTPUT_VARIABLE GIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE) 
message(STATUS "Version v${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION} with git hash #${GIT_HASH}")