dist: xenial
sudo: true
language: cpp
compiler:
  - gcc
before_install: 
  - pip install --user cpp-coveralls
script:
  - sudo apt-get update
  - sudo apt-get install doxygen catch g++-6 libcairo2-dev libxt-dev doxygen libxml2-dev libsdl2-dev ncurses-dev libxext-dev libswscale-dev libprotobuf-c-dev geographiclib-doc libgeographic-dev libasio-dev libtinyxml2-dev gradle libgeographic-dev
  - mkdir build && cd build && cmake -DENABLE_COVERAGE=ON  -DCMAKE_CXX_COMPILER=g++-6 ..  
  - make
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
after_success:
  - cd .. && pwd && ls -hal ./build/CMakeFiles/ $$ find
  - bash <(curl -s https://codecov.io/bash)
