dist: xenial
sudo: true
language: cpp
compiler:
  - gcc
before_install:
  - git submodule update --init --recursive
script:
  - sudo apt-get update
  - sudo apt-get install doxygen catch valgrind libcairo2-dev libxt-dev doxygen libxml2-dev libsdl2-dev ncurses-dev libxext-dev libswscale-dev libprotobuf-c-dev geographiclib-doc libgeographic-dev libasio-dev libtinyxml2-dev gradle libgeographic-dev
  - mkdir build && cd build && cmake -DENABLE_COVERAGE=ON ..  
  - make
  - xvfb-run --server-args="-screen 0 1024x768x24" ctest -T memcheck
after_success:
  - cd ..
  - bash <(curl -s https://codecov.io/bash)
