dist: xenial
sudo: true
language: cpp
before_install: 
  - sudo apt-get update
  - sudo apt-get install doxygen libcairo2-dev libxt-dev doxygen libxml2-dev libsdl2-dev ncurses-dev libxext-dev
compiler:
  - gcc
script:
  - mkdir build && cd build %% cmake .. && make
