name: "Build : Cyclone"

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo apt-get --no-install-recommends install doxygen libgtk-3-dev valgrind libcairo2-dev libpango1.0-dev libxt-dev doxygen libxml2-dev ncurses-dev libxext-dev libswscale-dev libprotobuf-c-dev geographiclib-doc libgeographic-dev libasio-dev libtinyxml2-dev gradle libgeographic-dev libprotobuf-dev protobuf-compiler
          sudo apt-get --no-install-recommends install autoconf automake libtool curl make g++ unzip

      - name: Pkgconfig
        run: pkg-config gtk+-3.0  --libs --cflags

      - name: CMake and Build
        run: mkdir build && cd build && cmake .. -DENABLE_COVERAGE=ON -DBUILD_TESTS=ON .. && make -j ${nproc}

      - name: CTest
        run: xvfb-run --server-args="-screen 0 1024x768x24" ctest -T memcheck

      - name: Post
        run: cd .. && bash <(curl -s https://codecov.io/bash)
