name: "Build Ubuntu Intel : Opensplice"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu-opensplice:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo apt-get --no-install-recommends install catch cpplint rpm python2-minimal libgtk-3-dev valgrind libcairo2-dev \
          libpango1.0-dev libxt-dev doxygen libxml2-dev ncurses-dev libxext-dev libswscale-dev libprotobuf-c-dev \
          geographiclib-doc libgeographic-dev libgeographic-dev libprotobuf-dev sqlite3 libleveldb-dev \
          protobuf-compiler autoconf automake libtool curl make g++ unzip gawk flex bison lsb-release && \
          sudo apt remove  *jdk* -y

      - name: Configure
        run: |
          unset JAVA_HOME && \
          unset JAVAC_COMMAND && \
          mkdir build && \
          cd build && \
          cmake -DDDS=OSPL-CE .. && \
          make -j ${nproc}

      - name: Package
        run: cd $HOME/build && cpack -G RPM && PACKAGE=$(ls ./build/*.rpm)

      # - name: CTest
      #   run: xvfb-run --server-args="-screen 0 1024x768x24" ctest -T memcheck

      - name: Post
        run: cd .. && bash <(curl -s https://codecov.io/bash)

      - name: Archive packaged .rpm
        uses: actions/upload-artifact@v3
        with:
          name: $PACKAGE
          path: $PACKAGE

      - name: Archive logs
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            build/_CPack_Packages/Linux/RPM/PreinstallOutput.log
            build/compile_commands.json
            build/external/libnmea/build/CMakeFiles/CMakeOutput.log
            build/external/cyclonedds/build/CMakeFiles/CMakeOutput.log
            build/external/cyclonedds-cxx/build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeOutput.log
          retention-days: 30
