name: "Build Windows Intel : Cyclone"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-msys2-cyclone:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: cmake git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3  mingw-w64-x86_64-gcc mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-nsis
      - name: CMake and Build
        run: |
          echo 'Running in MSYS2!' && \
          mkdir build && \
          cd build && cmake --help && \
          cmake -G "Unix Makefiles" .. -DDDS=CYCLONE-CE .. && \
          make
      - name: Install
        run: |
          cd build && make install
      - name: Package
        run: |
          cd build && cpack

          