name: "Build Windows Intel : Cyclone"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-msys-cyclone:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: cmake git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3  mingw-w64-x86_64-gcc mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-nsis
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!' \
          find / | grep g++ \
          which g++
      - name: CMake and Build
        run: mkdir build && cd build && cmake -G "Unix Makefiles" .. -DDDS=CYCLONE-CE .. && make
      - name: Install
        run: cd build && make install
      - name: Package
        run: cd build && cpack

          