

name: "Build : Doxygen"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-ubuntu-doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apt Update
        run: sudo apt-get update

      - name: Apt Install
        run: |
          sudo apt-get --no-install-recommends install doxygen graphviz

      - name: Doxygen
        run: doxygen

      - name: Archive doxygen results
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-html
          path: html
          retention-days: 60