name: "Build Windows Intel : Cyclone"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-msys2-cyclone:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    # Map a step output to a job output
    outputs:
      package_name: ${{ steps.package.outputs.NSIS_PACKAGE }}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git base-devel mingw-w64-x86_64-cmake mingw-w64-x86_64-cairo mingw-w64-x86_64-cairo mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3  mingw-w64-x86_64-gcc mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-nsis
      - name: CMake and Build
        run: |
          echo 'Running in MSYS2!' && \
          mkdir build && \
          cd build && \
          cmake -G "MSYS Makefiles" .. -DDDS=CYCLONE-CE .. && \
          make 
          find c:/ | grep cairo-2
      # - name: Install
      #   run: |
      #     cd build && make install
      # - name: Package
      #   run: |
      #     cd build && cpack && \
      #     echo "NSIS_PACKAGE=$(ls *.exe)" >> $GITHUB_ENV && echo "NSIS_PACKAGE=$(ls *.exe)" >> $GITHUB_OUTPUT
      # - name: Archive packaged .exe
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ env.NSIS_PACKAGE }}
      #     path: build/${{ env.NSIS_PACKAGE }}
      #     retention-days: 30

          