name: "Build CentOS : Cyclone"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-centos-cyclone:
    runs-on: ubuntu-22.04
    container: centos:8

    steps:
      - uses: actions/checkout@v3
      - name: Dnf Update
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
          dnf update -y && \
          dnf install epel-release -y && dnf update -y && \
          dnf localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm -y && \
          dnf config-manager --set-enabled powertools -y

      - name: Dnf Install
        run: |
          dnf install git cmake gcc-c++ python2-pip cairo-devel libXt-devel doxygen libxml2-devel ncurses-devel libXext-devel ffmpeg-devel protobuf-devel protobuf-compiler GeographicLib-devel gtk3-devel -y && \
          pip2 install cpplint

      - name: CMake and Build
        run: mkdir build && cd build && cmake .. -DDDS=CYCLONE-CE .. && make -j $(nproc)

      - name: Package for CentOS (.rpm)
        run: cd build && cpack -G RPM && echo "RPM_PACKAGE=$(ls *.rpm)" >> $GITHUB_ENV 

      - name: Archive packaged .deb
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DEB_PACKAGE }}
          path: build/${{ env.DEB_PACKAGE }}
          retention-days: 30