name: "Build Ubuntu : Cyclone"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build-centos-cyclone:
    runs-on: ubuntu-22.04
    container: centos:8

    steps:
      - uses: actions/checkout@v3
      - name: Dnf Update
        run: |
          dnf update

      # - name: CMake and Build
      #   run: mkdir build && cd build && cmake .. -DDDS=CYCLONE-CE .. && make -j $(nproc)

