# Simple workflow for deploying static content to GitHub Pages
name: "Build : Doxygen"

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Apt Update
        run: sudo apt-get update
      - name: Apt Install
        run: sudo apt-get --no-install-recommends install xvfb doxygen graphviz wget plantuml imagemagick libgtk-3-dev libswscale-dev libprotobuf-c-dev geographiclib-doc libgeographic-dev libgeographic-dev libprotobuf-dev protobuf-compiler
      - name: Dummy X11
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Doxygen
        run: |
          export DISPLAY=':99.0' && \
          export MAJOR=$(sed -n '1p' < version) && \
          export MINOR=$(sed -n '2p' < version) && \
          export PATCH=$(sed -n '3p' < version) && \
          export GIT_HASH=$(git rev-parse --short HEAD) && \
          mkdir -p /var/log && \
          touch /var/log/gva.log && \
          echo "Current version ${SEM_VERSION} with #${GIT_HASH}" && \
          mkdir build && \
          cd build && \
          cmake .. && \
          ls -hal && \
          make doxygen && \
          wget https://img.shields.io/badge/version-${SEM_VERSION}-blue.svg -O ../docs/version.svg
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the docs
          path: "docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
